//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationServer.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Sections
    {
        [IgnoreDataMember]
        public System.Guid Id { get; set; }
        [IgnoreDataMember]
        public string Section { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Location { get; set; }
    }
}
